apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api-gateway
  labels:
    app: api-gateway-app
spec:
  replicas: 2  # Modify replicas according to your case
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      containers:
      - name: api-gateway-container
        image: 339712719504.dkr.ecr.us-east-1.amazonaws.com/fcjws2:api-gateway-d966430
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-info
  labels:
    app: info-service
spec:
  replicas: 2  # Modify replicas according to your case
  selector:
    matchLabels:
      app: info-service
  template:
    metadata:
      labels:
        app: info-service
    spec:
      containers:
      - name: info-service-container
        image: 339712719504.dkr.ecr.us-east-1.amazonaws.com/fcjws2:info-d966430
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-order
  labels:
    app: order-service
spec:
  replicas: 2  # Modify replicas according to your case
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service-container
        image: 339712719504.dkr.ecr.us-east-1.amazonaws.com/fcjws2:order-d966430
        imagePullPolicy: Always
        ports:
        - containerPort: 3001