apiVersion: v1
kind: Service
metadata:
  name: service-api-gateway
  labels:
    app: api-gateway-app
spec:
  type: LoadBalancer
  selector:
    app: api-gateway-app
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: info-service
  labels:
    app: info-service
spec:
  type: NodePort
  selector:
    app: info-service
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: NodePort
  selector:
    app: order-service
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP